### ISSUE TITLE
Order By

### ISSUE THREAD

**Issue by andregeges** [dmyers/laravel-storage#12]
Storage::files('images');

How can i filter command above order by a-z

**Comment by dmyers** [comment]
That is a good feature request, though I'm unsure how I would handle it for every adapter just yet.

I think what might be nice is if I switch to collections instead of returning simply arrays then you could pass a closure to filter on it.

**Comment by andregeges** [comment]
thanks..

**Comment by dmyers** [comment]
What I would recommend is wrapping the results in `Collection` objects and using many of the built in methods which are really helpful instead of baking it into this package.

Though it is on my todo list to automatically return Collection objects.
